/** Original question bank — fan-made demo, not from any TV show. */
window.QUIZ_BANK = [
  {d:"easy",q:"What is the capital of Northern Ireland?",o:["Dublin","Belfast","Cardiff","Edinburgh"],a:1},
  {d:"easy",q:"How many players are on a football team on the pitch?",o:["9","10","11","12"],a:2},
  {d:"easy",q:"Which planet is known as the Red Planet?",o:["Venus","Mars","Jupiter","Saturn"],a:1},
  {d:"easy",q:"What colour are the stars on the flag of the United States?",o:["Red","Blue","White","Gold"],a:2},
  {d:"easy",q:"Which ocean lies west of the British Isles?",o:["Indian","Atlantic","Pacific","Arctic"],a:1},
  {d:"easy",q:"What is H2O commonly known as?",o:["Salt","Water","Hydrogen","Oxygen"],a:1},
  {d:"easy",q:"Which day comes after Friday?",o:["Thursday","Saturday","Sunday","Monday"],a:1},
  {d:"easy",q:"How many sides does a triangle have?",o:["2","3","4","5"],a:1},
  {d:"easy",q:"Which UK coin is the largest in common circulation?",o:["5p","£1","£2","50p"],a:2},
  {d:"easy",q:"What do bees collect from flowers?",o:["Leaves","Nectar","Soil","Rain"],a:1},
  {d:"easy",q:"Which sport uses a wicket?",o:["Rugby","Cricket","Tennis","Golf"],a:1},
  {d:"easy",q:"What is the first month of the year?",o:["March","January","April","June"],a:1},
  {d:"easy",q:"Which animal is known as man's best friend?",o:["Cat","Dog","Horse","Rabbit"],a:1},
  {d:"easy",q:"What gas do plants absorb from the air?",o:["Oxygen","Carbon dioxide","Nitrogen","Helium"],a:1},
  {d:"easy",q:"Which Scottish city hosts the annual Fringe festival?",o:["Glasgow","Edinburgh","Aberdeen","Dundee"],a:1},
  {d:"easy",q:"How many minutes are in one hour?",o:["30","45","60","90"],a:2},
  {d:"easy",q:"Which instrument has black and white keys?",o:["Guitar","Piano","Drum","Flute"],a:1},
  {d:"easy",q:"What is the largest mammal on Earth?",o:["Elephant","Blue whale","Giraffe","Shark"],a:1},
  {d:"easy",q:"Which Welsh city is home to the Principality Stadium?",o:["Swansea","Cardiff","Newport","Wrexham"],a:1},
  {d:"easy",q:"What do you call a young sheep?",o:["Calf","Lamb","Kid","Pup"],a:1},
  {d:"easy",q:"Which season comes after winter in the UK?",o:["Autumn","Spring","Summer","Monsoon"],a:1},
  {d:"easy",q:"What is the boiling point of water in °C?",o:["50","100","150","200"],a:1},
  {d:"easy",q:"Which country invented tea drinking as a national habit?",o:["France","China","Brazil","Canada"],a:1},
  {d:"easy",q:"What is the main language spoken in Brazil?",o:["Spanish","Portuguese","French","Italian"],a:1},
  {d:"medium",q:"In which year did the Titanic sink?",o:["1905","1912","1920","1898"],a:1},
  {d:"medium",q:"Who wrote 'Pride and Prejudice'?",o:["Charles Dickens","Jane Austen","Emily Brontë","Virginia Woolf"],a:1},
  {d:"medium",q:"What is the chemical symbol for gold?",o:["Go","Gd","Au","Ag"],a:2},
  {d:"medium",q:"Which river flows through London?",o:["Mersey","Thames","Tyne","Severn"],a:1},
  {d:"medium",q:"How many counties are in the Republic of Ireland?",o:["24","26","32","28"],a:1},
  {d:"medium",q:"Which scientist proposed the theory of relativity?",o:["Newton","Einstein","Galileo","Tesla"],a:1},
  {d:"medium",q:"What is the tallest mountain in the British Isles?",o:["Snowdon","Ben Nevis","Scafell Pike","Slieve Donard"],a:1},
  {d:"medium",q:"Which king was on the English throne during the Spanish Armada?",o:["Henry VIII","Elizabeth I","James I","Charles I"],a:1},
  {d:"medium",q:"What is the smallest prime number?",o:["0","1","2","3"],a:2},
  {d:"medium",q:"Which element has atomic number 1?",o:["Helium","Hydrogen","Lithium","Carbon"],a:1},
  {d:"medium",q:"In chess, which piece can only move diagonally?",o:["Rook","Knight","Bishop","Queen"],a:2},
  {d:"medium",q:"What is the capital of Australia?",o:["Sydney","Melbourne","Canberra","Perth"],a:2},
  {d:"medium",q:"Which organ pumps blood around the body?",o:["Liver","Heart","Lung","Kidney"],a:1},
  {d:"medium",q:"Who painted the Mona Lisa?",o:["Van Gogh","Da Vinci","Picasso","Rembrandt"],a:1},
  {d:"medium",q:"What is the longest river in the UK?",o:["Thames","Severn","Trent","Wye"],a:1},
  {d:"medium",q:"Which planet is closest to the Sun?",o:["Venus","Mercury","Mars","Earth"],a:1},
  {d:"medium",q:"What does BBC stand for?",o:["British Broadcasting Corporation","British Board of Culture","Broadcast Bureau of Britain","British Blog Channel"],a:0},
  {d:"medium",q:"Which war ended in 1945?",o:["World War I","World War II","Korean War","Vietnam War"],a:1},
  {d:"medium",q:"What is the square root of 144?",o:["10","11","12","14"],a:2},
  {d:"medium",q:"Which gas makes up most of Earth's atmosphere?",o:["Oxygen","Nitrogen","Carbon dioxide","Argon"],a:1},
  {d:"medium",q:"Who was the first man on the Moon?",o:["Buzz Aldrin","Neil Armstrong","Yuri Gagarin","John Glenn"],a:1},
  {d:"medium",q:"Which Irish county is nicknamed the Rebel County?",o:["Kerry","Cork","Galway","Donegal"],a:1},
  {d:"medium",q:"What is the currency of Japan?",o:["Won","Yen","Ringgit","Baht"],a:1},
  {d:"medium",q:"Which Shakespeare play features Romeo and Juliet?",o:["Hamlet","Macbeth","Romeo and Juliet","Othello"],a:2},
  {d:"hard",q:"What is the capital of Kazakhstan?",o:["Tashkent","Astana","Bishkek","Dushanbe"],a:1},
  {d:"hard",q:"In which year was the Magna Carta signed?",o:["1066","1215","1415","1649"],a:1},
  {d:"hard",q:"What is the hardest natural substance on Earth?",o:["Gold","Diamond","Quartz","Iron"],a:1},
  {d:"hard",q:"Who developed the polio vaccine in 1955?",o:["Pasteur","Salk","Jenner","Fleming"],a:1},
  {d:"hard",q:"Which element is liquid at room temperature besides mercury?",o:["Gallium","Bromine","Cesium","Francium"],a:1},
  {d:"hard",q:"What is the speed of light in km/s (approx)?",o:["150,000","300,000","450,000","600,000"],a:1},
  {d:"hard",q:"Which English king had six wives?",o:["Henry VII","Henry VIII","Edward VI","Richard III"],a:1},
  {d:"hard",q:"What is the largest desert in the world?",o:["Sahara","Antarctic","Arabian","Gobi"],a:1},
  {d:"hard",q:"Who wrote '1984'?",o:["Huxley","Orwell","Bradbury","Atwood"],a:1},
  {d:"hard",q:"What is the smallest country by area?",o:["Monaco","Vatican City","San Marino","Liechtenstein"],a:1},
  {d:"hard",q:"Which bone is the longest in the human body?",o:["Humerus","Femur","Tibia","Radius"],a:1},
  {d:"hard",q:"In what year did the Berlin Wall fall?",o:["1987","1989","1991","1985"],a:1},
  {d:"hard",q:"What is the chemical formula for table salt?",o:["NaCl","KCl","CaCO3","H2SO4"],a:0},
  {d:"hard",q:"Which planet has the most moons (as of 2024)?",o:["Jupiter","Saturn","Uranus","Neptune"],a:1},
  {d:"hard",q:"Who painted 'The Persistence of Memory' with melting clocks?",o:["Dalí","Magritte","Miró","Picasso"],a:0},
  {d:"hard",q:"What language has the most native speakers worldwide?",o:["English","Mandarin Chinese","Spanish","Hindi"],a:1},
  {d:"hard",q:"Which Irish poet wrote 'The Lake Isle of Innisfree'?",o:["Heaney","Yeats","Kavanagh","Joyce"],a:1},
  {d:"hard",q:"What is Avogadro's number (order of magnitude)?",o:["10²³","10¹⁵","10³⁰","10¹⁸"],a:0},
  {d:"hard",q:"Which battle ended Napoleon's Hundred Days?",o:["Austerlitz","Waterloo","Trafalgar","Leipzig"],a:1},
  {d:"hard",q:"What is the capital of Canada?",o:["Toronto","Ottawa","Montreal","Vancouver"],a:1},
  {d:"hard",q:"Which vitamin is produced when skin is exposed to sunlight?",o:["A","C","D","K"],a:2},
  {d:"hard",q:"Who discovered penicillin?",o:["Lister","Fleming","Koch","Curie"],a:1},
  {d:"hard",q:"What is the SI unit of electrical resistance?",o:["Volt","Ohm","Ampere","Watt"],a:1},
  {d:"hard",q:"Which ancient wonder was located in Alexandria?",o:["Colossus","Lighthouse","Hanging Gardens","Mausoleum"],a:1},
  {d:"hard",q:"What is the longest bone in the human arm?",o:["Radius","Ulna","Humerus","Clavicle"],a:2},
  {d:"expert",q:"Who won the Nobel Prize in Literature in 1995?",o:["Heaney","Beckett","Shaw","Yeats"],a:0},
  {d:"expert",q:"What is the half-life of Carbon-14 (approx)?",o:["573 years","5,730 years","57,300 years","573,000 years"],a:1},
  {d:"expert",q:"Which treaty established the European Union in 1993?",o:["Treaty of Rome","Maastricht","Lisbon","Nice"],a:1},
  {d:"expert",q:"In computing, what does SHA stand for in SHA-256?",o:["Secure Hash Algorithm","System Host Access","Signed Header Auth","Storage Hash Archive"],a:0},
  {d:"expert",q:"Who composed 'The Four Seasons'?",o:["Bach","Vivaldi","Handel","Mozart"],a:1},
  {d:"expert",q:"What is the capital of Bhutan?",o:["Kathmandu","Thimphu","Dhaka","Vientiane"],a:1},
  {d:"expert",q:"Which philosopher wrote 'Critique of Pure Reason'?",o:["Hegel","Kant","Nietzsche","Descartes"],a:1},
  {d:"expert",q:"What is the rarest blood type in the UK population?",o:["O negative","AB negative","B negative","A negative"],a:1},
  {d:"expert",q:"In which year did Ireland join the European Communities?",o:["1973","1981","1967","1995"],a:0},
  {d:"expert",q:"What particle was confirmed at CERN in 2012?",o:["Graviton","Higgs boson","Tachyon","Gluon"],a:1},
  {d:"expert",q:"Who was UK Prime Minister during the Falklands War?",o:["Callaghan","Thatcher","Major","Wilson"],a:1},
  {d:"expert",q:"What is the deepest ocean trench?",o:["Puerto Rico","Mariana","Java","Tonga"],a:1},
  {d:"expert",q:"Which artist cut off part of his own ear?",o:["Gauguin","Van Gogh","Cézanne","Monet"],a:1},
  {d:"expert",q:"What does the acronym CRISPR relate to?",o:["Gene editing","Rocket guidance","Climate modelling","Cryptography"],a:0},
  {d:"expert",q:"Who wrote 'Waiting for Godot'?",o:["Pinter","Beckett","Stoppard","Osborne"],a:1},
  {d:"expert",q:"What is Planck's constant (order of magnitude)?",o:["10⁻³⁴ J·s","10⁻²³ J·s","10⁻¹⁵ J·s","10⁻⁴⁴ J·s"],a:0},
  {d:"expert",q:"Which Roman emperor built a wall in northern Britain?",o:["Nero","Hadrian","Augustus","Caligula"],a:1},
  {d:"expert",q:"What is the largest internal organ in the human body?",o:["Brain","Liver","Lung","Heart"],a:1},
  {d:"expert",q:"In which city was the Titanic built?",o:["Liverpool","Belfast","Glasgow","Southampton"],a:1},
  {d:"expert",q:"What is the chemical symbol for tungsten?",o:["Tu","W","Tg","Tn"],a:1},
  {d:"expert",q:"Who formulated the laws of motion and universal gravitation?",o:["Kepler","Newton","Copernicus","Faraday"],a:1},
  {d:"expert",q:"Which country has the most time zones?",o:["USA","Russia","France","China"],a:2},
  {d:"expert",q:"What year did the Good Friday Agreement sign?",o:["1996","1998","2000","1994"],a:1}
];
