#!/usr/bin/env python3
"""Generate games/the-pursuit/questions.js with unique IDs (run after editing QUESTIONS)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "games" / "the-pursuit" / "questions.js"

# fmt: off
# Each: (difficulty, question, [A,B,C,D], correct_index 0-3)
QUESTIONS = [
# --- EASY (UK pub-quiz / chaser-style general knowledge) ---
("easy","What is the capital of England?",["London","Manchester","York","Bristol"],0),
("easy","Which sea lies east of England?",["North Sea","Red Sea","Black Sea","Caspian Sea"],0),
("easy","How many days are in a leap year?",["364","365","366","367"],2),
("easy","What colour is a emerald?",["Blue","Green","Red","Yellow"],1),
("easy","Which bird is on the Twitter/X logo?",["Eagle","Parrot","Bird (generic)","Owl"],2),
("easy","What is frozen water called?",["Steam","Ice","Fog","Rain"],1),
("easy","Which country has the Eiffel Tower?",["Germany","France","Italy","Spain"],1),
("easy","How many legs does a spider have?",["6","8","10","12"],1),
("easy","What is the capital of Scotland?",["Glasgow","Edinburgh","Inverness","Stirling"],1),
("easy","Which sport is Wimbledon associated with?",["Golf","Tennis","Cricket","Rugby"],1),
("easy","What is the largest planet in our solar system?",["Earth","Mars","Jupiter","Neptune"],2),
("easy","Which Irish city is known as the Rebel County's main city?",["Dublin","Cork","Limerick","Galway"],1),
("easy","What do caterpillars turn into?",["Bees","Butterflies","Spiders","Beetles"],1),
("easy","Which metal is liquid at room temperature?",["Iron","Mercury","Copper","Gold"],1),
("easy","What is the capital of Wales?",["Swansea","Cardiff","Newport","Wrexham"],1),
("easy","How many continents are there?",["5","6","7","8"],2),
("easy","Which fruit is traditionally in a crumble?",["Banana","Apple","Grape","Melon"],1),
("easy","What is the name of the UK national anthem?",["Jerusalem","God Save the King","Rule Britannia","Land of Hope"],1),
("easy","Which animal says 'moo'?",["Sheep","Cow","Pig","Horse"],1),
("easy","What is the opposite of hot?",["Warm","Cold","Mild","Cool"],1),
("easy","Which planet do we live on?",["Mars","Earth","Venus","Mercury"],1),
("easy","What is the capital of the Republic of Ireland?",["Belfast","Dublin","Cork","Galway"],1),
("easy","Which chess piece can jump over others?",["Bishop","Knight","Rook","Queen"],1),
("easy","What is the main ingredient in bread?",["Rice","Flour","Sugar","Corn"],1),
("easy","Which ocean is the largest?",["Atlantic","Indian","Pacific","Arctic"],2),
("easy","How many sides does a square have?",["3","4","5","6"],1),
("easy","What is the capital of France?",["Lyon","Paris","Nice","Marseille"],1),
("easy","Which season is Christmas in the UK?",["Summer","Winter","Spring","Autumn"],1),
("easy","What gas do humans breathe in?",["Carbon dioxide","Oxygen","Helium","Nitrogen"],1),
("easy","Which is a primary colour?",["Green","Red","Purple","Orange"],1),
("easy","What is the tallest animal?",["Elephant","Giraffe","Horse","Bear"],1),
("easy","Which country is the Great Wall in?",["Japan","China","Korea","India"],1),
("easy","What is 10 × 10?",["50","100","1000","20"],1),
("easy","Which instrument has six strings typically?",["Piano","Guitar","Flute","Trumpet"],1),
("easy","What is the capital of Northern Ireland?",["Dublin","Belfast","Cardiff","Edinburgh"],1),
("easy","How many players on a rugby union team on the pitch?",["11","13","15","17"],2),
("easy","Which star provides Earth with light?",["The Moon","The Sun","Mars","Polaris"],1),
("easy","What is the main language of Spain?",["Portuguese","Spanish","Italian","Catalan only"],1),
("easy","Which body part pumps blood?",["Lung","Heart","Liver","Brain"],1),
("easy","What is the freezing point of water in °C?",["0","32","100","-10"],0),
("easy","Which county is Manchester in?",["Yorkshire","Greater Manchester","Essex","Kent"],1),
("easy","What is a baby cat called?",["Pup","Kitten","Calf","Chick"],1),
("easy","Which direction does the sun rise?",["West","East","North","South"],1),
("easy","How many hours in a day?",["12","24","48","36"],1),
("easy","What is the capital of Italy?",["Milan","Rome","Venice","Naples"],1),
("easy","Which sport uses a puck?",["Football","Ice hockey","Cricket","Boxing"],1),
("easy","What shape is a football?",["Cube","Sphere","Pyramid","Cylinder"],1),
("easy","Which is the longest river in Ireland?",["Liffey","Shannon","Bann","Barrow"],1),
("easy","What do you call a house made of ice?",["Cabin","Igloo","Tent","Yurt"],1),
("easy","Which month has Valentine's Day?",["January","February","March","April"],1),
("easy","What is the capital of Spain?",["Barcelona","Madrid","Seville","Valencia"],1),
("easy","Which animal is the symbol of the USA?",["Bear","Bald eagle","Lion","Wolf"],1),
("easy","How many pennies in one pound?",["10","100","1000","50"],1),
("easy","What colour are bananas when ripe?",["Blue","Yellow","Red","Purple"],1),
("easy","Which organ helps you breathe?",["Heart","Lungs","Stomach","Kidneys"],1),
("easy","What is the capital of Germany?",["Munich","Berlin","Hamburg","Frankfurt"],1),
("easy","Which game uses kings, queens and jacks?",["Monopoly","Cards","Chess only","Dominoes"],1),
("easy","What is the largest land animal?",["Rhino","African elephant","Hippo","Giraffe"],1),
("easy","Which Irish symbol is a three-leaf clover?",["Rose","Shamrock","Thistle","Daffodil"],1),
("easy","What do bees make?",["Milk","Honey","Silk","Wax only"],1),
("easy","Which planet has rings visible from Earth?",["Mars","Saturn","Venus","Mercury"],1),
("easy","What is the capital of Portugal?",["Porto","Lisbon","Faro","Braga"],1),
("easy","How many strings on a standard violin?",["4","6","8","12"],0),
("easy","Which food is associated with Halloween?",["Turkey","Pumpkin","Ham","Salmon"],1),
("easy","What is the smallest ocean?",["Pacific","Arctic","Atlantic","Indian"],1),
("easy","Which sport is the Ashes about?",["Football","Cricket","Rugby","Golf"],1),
("easy","What is the capital of Austria?",["Prague","Vienna","Budapest","Zurich"],1),
("easy","Which gas makes voices squeaky?",["Oxygen","Helium","CO2","Nitrogen"],1),
("easy","What is the main colour of grass?",["Blue","Green","Yellow","Brown"],1),
("easy","Which day is Remembrance Sunday near?",["Easter","11 November","Christmas","Halloween"],1),
("easy","What is the capital of Norway?",["Stockholm","Oslo","Copenhagen","Helsinki"],1),
("easy","Which animal has a trunk?",["Giraffe","Elephant","Rhino","Horse"],1),
("easy","How many wheels on a bicycle?",["1","2","3","4"],1),
("easy","What is the capital of Greece?",["Rome","Athens","Istanbul","Sofia"],1),
("easy","Which fruit keeps the doctor away?",["Pear","Apple","Peach","Plum"],1),
("easy","What is the capital of the Netherlands?",["Rotterdam","Amsterdam","Utrecht","The Hague"],1),
("easy","Which sport uses a net and shuttlecock?",["Tennis","Badminton","Volleyball","Squash"],1),
("easy","What is the hardest natural material?",["Gold","Diamond","Iron","Silver"],1),
("easy","Which planet is closest to Earth?",["Venus","Mars","Mercury","Jupiter"],0),
("easy","What is the capital of Belgium?",["Antwerp","Brussels","Bruges","Ghent"],1),
("easy","Which bird cannot fly but runs fast?",["Penguin","Ostrich","Eagle","Sparrow"],1),
("easy","How many cents in a euro?",["10","100","1000","50"],1),
("easy","What is the capital of Poland?",["Krakow","Warsaw","Gdansk","Wroclaw"],1),
("easy","Which sea separates UK and France?",["North Sea","English Channel","Irish Sea","Baltic"],1),
("easy","What is the capital of Denmark?",["Oslo","Copenhagen","Stockholm","Reykjavik"],1),
("easy","Which organ controls the body?",["Heart","Brain","Liver","Skin"],1),
("easy","What is the capital of Sweden?",["Oslo","Stockholm","Helsinki","Bergen"],1),
("easy","Which sport uses a try line?",["Football","Rugby","Tennis","Snooker"],1),
("easy","What is the capital of Finland?",["Oslo","Helsinki","Tallinn","Riga"],1),
("easy","Which metal is in coins with 'copper' colour?",["Gold","Copper or copper-plated","Silver","Platinum"],1),
("easy","What is the capital of Czech Republic?",["Bratislava","Prague","Vienna","Budapest"],1),
("easy","Which animal lives in a dam?",["Beaver","Fox","Badger","Otter"],0),
("easy","What is the capital of Hungary?",["Prague","Budapest","Bucharest","Sofia"],1),
("easy","Which planet is known as the Morning Star?",["Mars","Venus","Jupiter","Saturn"],1),
("easy","What is the capital of Switzerland?",["Zurich","Bern","Geneva","Basel"],1),
("easy","Which fish is Nemo?",["Shark","Clownfish","Salmon","Tuna"],1),
("easy","What is the capital of Turkey?",["Istanbul","Ankara","Izmir","Antalya"],1),
("easy","Which sport uses a green jacket prize?",["Tennis","Golf","Cricket","Boxing"],1),
("easy","What is the capital of Russia?",["St Petersburg","Moscow","Kiev","Minsk"],1),
("easy","Which insect makes silk?",["Bee","Silkworm","Ant","Fly"],1),
("easy","What is the capital of Egypt?",["Alexandria","Cairo","Luxor","Giza"],1),
("easy","Which sport is played at Lord's?",["Football","Cricket","Rugby","Hockey"],1),
("easy","What is the capital of India?",["Mumbai","New Delhi","Kolkata","Chennai"],1),
("easy","Which animal is black and white and eats bamboo?",["Panda","Zebra","Skunk","Penguin"],0),
("easy","What is the capital of Japan?",["Osaka","Tokyo","Kyoto","Hiroshima"],1),
("easy","Which sport uses a slam dunk?",["Football","Basketball","Tennis","Golf"],1),
("easy","What is the capital of China?",["Shanghai","Beijing","Hong Kong","Guangzhou"],1),
("easy","Which animal is the king of the jungle?",["Tiger","Lion","Bear","Wolf"],1),
("easy","What is the capital of Canada?",["Toronto","Ottawa","Montreal","Vancouver"],1),
("easy","Which sport uses a hole in one?",["Cricket","Golf","Rugby","Darts"],1),
("easy","What is the capital of USA?",["New York","Washington D.C.","Los Angeles","Chicago"],1),
("easy","Which animal carries a pouch?",["Kangaroo","Koala","Platypus","Emu"],0),
("easy","What is the capital of Australia?",["Sydney","Canberra","Melbourne","Perth"],1),
("easy","Which sport uses a bullseye?",["Football","Darts","Swimming","Rowing"],1),
("easy","What is the capital of Brazil?",["Rio","Brasília","São Paulo","Salvador"],1),
("easy","Which animal is the largest cat?",["Lion","Tiger","Leopard","Cheetah"],1),
("easy","What is the capital of Mexico?",["Cancún","Mexico City","Guadalajara","Tijuana"],1),
("easy","Which sport uses a scrum?",["Football","Rugby","Tennis","Cricket"],1),
("easy","What is the capital of Argentina?",["Buenos Aires","Santiago","Lima","Montevideo"],0),
("easy","Which animal has black and white stripes?",["Tiger","Zebra","Panda","Cow"],1),
("easy","What is the capital of South Africa (legislative)?",["Johannesburg","Cape Town","Pretoria","Durban"],1),
("easy","Which sport uses a penalty shootout?",["Cricket","Football","Golf","Snooker"],1),
("easy","What is the capital of New Zealand?",["Auckland","Wellington","Christchurch","Hamilton"],1),
("easy","Which animal hibernates in winter?",["Dog","Bear","Cat","Horse"],1),
("easy","What is the capital of Iceland?",["Oslo","Reykjavik","Stockholm","Bergen"],1),
("easy","Which sport uses a lane and freestyle?",["Football","Swimming","Golf","Archery"],1),
("easy","What is the capital of Thailand?",["Phuket","Bangkok","Chiang Mai","Pattaya"],1),
("easy","Which animal is man's best friend?",["Cat","Dog","Rabbit","Hamster"],1),
("easy","What is the capital of Vietnam?",["Ho Chi Minh City","Hanoi","Da Nang","Hue"],1),
("easy","Which sport uses a checkmate?",["Poker","Chess","Bridge","Bingo"],1),
("easy","What is the capital of South Korea?",["Busan","Seoul","Incheon","Daegu"],1),
("easy","Which animal has a long neck?",["Horse","Giraffe","Dog","Cat"],1),
("easy","What is the capital of Malaysia?",["Penang","Kuala Lumpur","Johor","Malacca"],1),
("easy","Which sport uses a oche line?",["Golf","Darts","Cricket","Rowing"],1),
("easy","What is the capital of Singapore?",["Singapore (city-state)","Jakarta","Bangkok","Manila"],0),
("easy","Which animal lives in the Arctic?",["Camel","Polar bear","Elephant","Kangaroo"],1),
("easy","What is the capital of Kenya?",["Mombasa","Nairobi","Kisumu","Nakuru"],1),
("easy","Which sport uses a wicket keeper?",["Football","Cricket","Tennis","Boxing"],1),
("easy","What is the capital of Nigeria?",["Lagos","Abuja","Kano","Ibadan"],1),
("easy","Which animal is known for changing colour?",["Dog","Chameleon","Cow","Sheep"],1),
("easy","What is the capital of Morocco?",["Casablanca","Rabat","Marrakech","Fez"],1),
("easy","Which sport uses a caddie?",["Tennis","Golf","Rugby","Swimming"],1),
("easy","What is the capital of Saudi Arabia?",["Jeddah","Riyadh","Mecca","Dubai"],1),
("easy","Which animal is the fastest land animal?",["Lion","Cheetah","Horse","Deer"],1),
("easy","What is the capital of UAE?",["Dubai","Abu Dhabi","Sharjah","Ajman"],1),
("easy","Which sport uses a pommel horse?",["Football","Gymnastics","Cricket","Hockey"],1),
("easy","What is the capital of Iran?",["Isfahan","Tehran","Shiraz","Tabriz"],1),
("easy","Which animal has tusks?",["Horse","Elephant","Cow","Sheep"],1),
("easy","What is the capital of Pakistan?",["Karachi","Islamabad","Lahore","Peshawar"],1),
("easy","Which sport uses a velodrome?",["Swimming","Cycling","Skiing","Skating"],1),
("easy","What is the capital of Bangladesh?",["Chittagong","Dhaka","Khulna","Sylhet"],1),
("easy","Which animal is Australia's national symbol?",["Kangaroo","Kiwi","Eagle","Lion"],0),
("easy","What is the capital of Philippines?",["Cebu","Manila","Davao","Quezon City"],1),
("easy","Which sport uses a steeplechase?",["Swimming","Athletics","Golf","Darts"],1),
("easy","What is the capital of Indonesia?",["Bali","Jakarta","Surabaya","Bandung"],1),
("easy","Which animal has a shell?",["Dog","Tortoise","Cat","Horse"],1),
("easy","What is the capital of Chile?",["Valparaíso","Santiago","Lima","Bogotá"],1),
("easy","Which sport uses a regatta?",["Football","Rowing","Cricket","Boxing"],1),
("easy","What is the capital of Colombia?",["Medellín","Bogotá","Cartagena","Cali"],1),
("easy","Which animal is known for loyalty to one mate?",["Fox","Swan","Rabbit","Mouse"],1),
("easy","What is the capital of Peru?",["Cusco","Lima","Arequipa","Trujillo"],1),
("easy","Which sport uses a slam?",["Golf","Volleyball","Cricket","Snooker"],1),
("easy","What is the capital of Venezuela?",["Maracaibo","Caracas","Valencia","Barquisimeto"],1),
("easy","Which animal is the symbol of peace?",["Lion","Dove","Snake","Wolf"],1),
("easy","What is the capital of Cuba?",["Santiago","Havana","Holguín","Camagüey"],1),
("easy","Which sport uses a snooker table?",["Tennis","Snooker","Rugby","Athletics"],1),
("easy","What is the capital of Jamaica?",["Montego Bay","Kingston","Ocho Rios","Negril"],1),
("easy","Which animal has antlers?",["Cow","Deer","Sheep","Goat"],1),
("easy","What is the capital of Haiti?",["Cap-Haïtien","Port-au-Prince","Gonaïves","Les Cayes"],1),
("easy","Which sport uses a pom-pom?",["Cricket","Cheerleading","Golf","Fencing"],1),
("easy","What is the capital of Dominican Republic?",["Santiago DR","Santo Domingo","Punta Cana","La Romana"],1),
("easy","Which animal is the largest bird?",["Eagle","Ostrich","Penguin","Emu"],1),
("easy","What is the capital of Panama?",["Colón","Panama City","David","Santiago"],1),
("easy","Which sport uses a foil?",["Swimming","Fencing","Golf","Cricket"],1),
("easy","What is the capital of Costa Rica?",["Limón","San José","Alajuela","Heredia"],1),
("easy","Which animal has a mane?",["Tiger","Male lion","Bear","Wolf"],1),
("easy","What is the capital of Guatemala?",["Antigua","Guatemala City","Quetzaltenango","Flores"],1),
("easy","Which sport uses a crease?",["Football","Cricket","Tennis","Boxing"],1),
("easy","What is the capital of Honduras?",["San Pedro Sula","Tegucigalpa","La Ceiba","Comayagua"],1),
("easy","Which animal is known for building webs?",["Bee","Spider","Ant","Fly"],1),
("easy","What is the capital of Nicaragua?",["León","Managua","Granada","Masaya"],1),
("easy","Which sport uses a javelin?",["Golf","Athletics","Swimming","Rowing"],1),
("easy","What is the capital of El Salvador?",["Santa Ana","San Salvador","San Miguel","Soyapango"],1),
("easy","Which animal is the national bird of the USA?",["Robin","Bald eagle","Turkey","Hawk"],1),
("easy","What is the capital of Belize?",["Belize City","Belmopan","San Ignacio","Dangriga"],1),
("easy","Which sport uses a shot put?",["Tennis","Athletics","Cricket","Hockey"],1),
("easy","What is the capital of Bahamas?",["Freeport","Nassau","Lucaya","Marsh Harbour"],1),
("easy","Which animal has a pouch and hops?",["Koala","Kangaroo","Wombat","Platypus"],1),
("easy","What is the capital of Barbados?",["Bridgetown","Speightstown","Oistins","Holetown"],0),
("easy","Which sport uses a high jump bar?",["Football","Athletics","Golf","Rowing"],1),
("easy","What is the capital of Trinidad and Tobago?",["San Fernando","Port of Spain","Chaguanas","Arima"],1),
("easy","Which animal is known for its memory?",["Fish","Elephant","Mouse","Snake"],1),
("easy","What is the capital of Malta?",["Mdina","Valletta","Sliema","Gozo"],1),
("easy","Which sport uses a long jump pit?",["Cricket","Athletics","Swimming","Boxing"],1),
("easy","What is the capital of Cyprus?",["Limassol","Nicosia","Paphos","Larnaca"],1),
("easy","Which animal is the symbol of Russia?",["Eagle","Bear","Lion","Wolf"],1),
("easy","What is the capital of Luxembourg?",["Esch","Luxembourg City","Differdange","Ettelbruck"],1),
("easy","Which sport uses a discus?",["Golf","Athletics","Tennis","Snooker"],1),
("easy","What is the capital of Monaco?",["Nice","Monaco (city-state)","Cannes","Menton"],1),
("easy","Which animal has a horn on its nose?",["Horse","Rhinoceros","Cow","Deer"],1),
("easy","What is the capital of Liechtenstein?",["Vaduz","Schaan","Balzers","Triesen"],0),
("easy","Which sport uses a hammer throw?",["Swimming","Athletics","Cricket","Fencing"],1),
("easy","What is the capital of Andorra?",["Andorra la Vella","Escaldes","Encamp","La Massana"],0),
("easy","Which animal is the largest reptile?",["Lizard","Saltwater crocodile","Turtle","Snake"],1),
("easy","What is the capital of San Marino?",["San Marino","Borgo","Serravalle","Domagnano"],0),
("easy","Which sport uses a pole vault?",["Football","Athletics","Golf","Rowing"],1),
("easy","What is the capital of Vatican City?",["Rome surrounds it","Vatican City","Milan","Florence"],1),
("easy","Which animal is known for playing dead?",["Fox","Opossum","Dog","Cat"],1),
("easy","What is the capital of Moldova?",["Bălți","Chișinău","Tiraspol","Cahul"],1),
("easy","Which sport uses a triathlon?",["Chess","Swim-bike-run","Darts","Snooker"],1),
("easy","What is the capital of Albania?",["Durrës","Tirana","Vlorë","Shkodër"],1),
("easy","Which animal is the national animal of Scotland?",["Lion","Unicorn","Stag","Eagle"],1),
("easy","What is the capital of North Macedonia?",["Bitola","Skopje","Ohrid","Tetovo"],1),
("easy","Which sport uses a decathlon?",["Golf","Athletics","Cricket","Boxing"],1),
("easy","What is the capital of Bosnia?",["Mostar","Sarajevo","Banja Luka","Tuzla"],1),
("easy","Which animal is the symbol of Wales?",["Lion","Red dragon","Unicorn","Stag"],1),
("easy","What is the capital of Serbia?",["Novi Sad","Belgrade","Niš","Kragujevac"],1),
("easy","Which sport uses a pentathlon?",["Swimming","Five events","Golf only","Darts"],1),
("easy","What is the capital of Croatia?",["Split","Zagreb","Dubrovnik","Rijeka"],1),
("easy","Which animal is the symbol of England?",["Dragon","Three lions","Eagle","Bear"],1),
("easy","What is the capital of Slovenia?",["Maribor","Ljubljana","Celje","Koper"],1),
("easy","Which sport uses a heptathlon?",["Cricket","Seven events","Golf","Rowing"],1),
("easy","What is the capital of Slovakia?",["Košice","Bratislava","Prešov","Žilina"],1),
("easy","Which animal is the symbol of Ireland?",["Dragon","Harp (national emblem)","Lion","Crown"],1),
("easy","What is the capital of Lithuania?",["Kaunas","Vilnius","Klaipėda","Šiauliai"],1),
("easy","Which sport uses a marathon distance?",["21 km","42.195 km","10 km","5 km"],1),
("easy","What is the capital of Latvia?",["Daugavpils","Riga","Liepāja","Jelgava"],1),
("easy","Which animal is the symbol of France?",["Lion","Rooster","Eagle","Bear"],1),
("easy","What is the capital of Estonia?",["Tartu","Tallinn","Pärnu","Narva"],1),
("easy","Which sport uses a sprint?",["Marathon","Short fast run","Swimming only","Golf"],1),
("easy","What is the capital of Belarus?",["Gomel","Minsk","Brest","Vitebsk"],1),
("easy","Which animal is the symbol of Germany?",["Eagle","Bear","Lion","Wolf"],1),
("easy","What is the capital of Ukraine?",["Kharkiv","Kyiv","Odessa","Lviv"],1),
("easy","Which sport uses a relay race?",["Golf","Passing baton","Cricket","Darts"],1),
("easy","What is the capital of Romania?",["Cluj","Bucharest","Timișoara","Iași"],1),
("easy","Which animal is the symbol of Italy?",["Eagle","Wolf (historical)","Lion","Bear"],1),
("easy","What is the capital of Bulgaria?",["Plovdiv","Sofia","Varna","Burgas"],1),
("easy","Which sport uses a hurdles race?",["Swimming","Running over barriers","Golf","Boxing"],1),
("easy","What is the capital of Georgia (country)?",["Batumi","Tbilisi","Kutaisi","Rustavi"],1),
("easy","Which animal is the symbol of Spain?",["Lion","Bull","Eagle","Bear"],1),
("easy","What is the capital of Armenia?",["Gyumri","Yerevan","Vanadzor","Abovyan"],1),
("easy","Which sport uses a steeplechase water jump?",["Golf","Athletics","Tennis","Snooker"],1),
("easy","What is the capital of Azerbaijan?",["Ganja","Baku","Sumqayit","Mingachevir"],1),
("easy","Which animal is the symbol of Canada?",["Eagle","Beaver","Lion","Tiger"],1),
("easy","What is the capital of Kazakhstan?",["Almaty","Astana","Shymkent","Karaganda"],1),
("easy","Which sport uses a walk (race walking)?",["Sprint","Heel-toe rule","Swimming","Rowing"],1),
("easy","What is the capital of Uzbekistan?",["Samarkand","Tashkent","Bukhara","Namangan"],1),
("easy","Which animal is the symbol of Australia?",["Kangaroo and emu","Lion","Eagle","Bear"],0),
("easy","What is the capital of Afghanistan?",["Kandahar","Kabul","Herat","Mazar-i-Sharif"],1),
("easy","Which sport uses a biathlon?",["Swimming","Skiing and shooting","Golf","Cricket"],1),
("easy","What is the capital of Iraq?",["Basra","Baghdad","Mosul","Erbil"],1),
("easy","Which animal is the symbol of India?",["Lion","Tiger (national animal)","Eagle","Bear"],1),
("easy","What is the capital of Syria?",["Aleppo","Damascus","Homs","Latakia"],1),
("easy","Which sport uses a curling stone?",["Football","Curling","Tennis","Boxing"],1),
("easy","What is the capital of Lebanon?",["Tripoli","Beirut","Sidon","Tyre"],1),
("easy","Which animal is the symbol of China?",["Eagle","Giant panda","Lion","Tiger"],1),
("easy","What is the capital of Jordan?",["Aqaba","Amman","Zarqa","Irbid"],1),
("easy","Which sport uses a luge?",["Swimming","Sled on ice","Golf","Cricket"],1),
("easy","What is the capital of Israel?",["Tel Aviv","Jerusalem","Haifa","Eilat"],1),
("easy","Which animal is the symbol of Japan?",["Lion","Koi/cultural (no single official)","Eagle","Bear"],1),
("easy","What is the capital of Palestine (claimed)?",["Gaza","Ramallah/East Jerusalem disputed","Hebron","Nablus"],1),
("easy","Which sport uses a bobsleigh?",["Golf","Winter sled","Tennis","Rowing"],1),
("easy","What is the capital of Oman?",["Salalah","Muscat","Sohar","Nizwa"],1),
("easy","Which animal is the symbol of South Korea?",["Lion","Tiger (cultural)","Eagle","Bear"],1),
("easy","What is the capital of Yemen?",["Aden","Sana'a","Taiz","Hodeidah"],1),
("easy","Which sport uses a skeleton sled?",["Cricket","Head-first sled","Golf","Darts"],1),
("easy","What is the capital of Qatar?",["Doha","Al Wakrah","Al Khor","Lusail"],0),
("easy","Which animal is the symbol of Brazil?",["Eagle","Jaguar (unofficial)","Lion","Tiger"],1),
("easy","What is the capital of Kuwait?",["Kuwait City","Salmiya","Hawalli","Jahra"],0),
("easy","Which sport uses a ski jump?",["Swimming","Flying off ramp","Golf","Boxing"],1),
("easy","What is the capital of Bahrain?",["Manama","Muharraq","Riffa","Hamad Town"],0),
("easy","Which animal is the symbol of Mexico?",["Eagle on cactus","Lion","Bear","Wolf"],0),
("easy","What is the capital of Myanmar?",["Mandalay","Naypyidaw","Yangon","Bago"],1),
("easy","Which sport uses a moguls ski run?",["Golf","Bumpy ski slope","Cricket","Rowing"],1),
("easy","What is the capital of Cambodia?",["Siem Reap","Phnom Penh","Battambang","Sihanoukville"],1),
("easy","Which animal is the symbol of Argentina?",["Lion","Sun of May","Eagle","Bear"],1),
("easy","What is the capital of Laos?",["Luang Prabang","Vientiane","Pakse","Savannakhet"],1),
("easy","Which sport uses a halfpipe?",["Swimming","Snowboard/skate ramp","Golf","Cricket"],1),
("easy","What is the capital of Mongolia?",["Erdenet","Ulaanbaatar","Darkhan","Choibalsan"],1),
("easy","Which animal is the symbol of South Africa?",["Lion","Springbok","Eagle","Bear"],1),
("easy","What is the capital of Nepal?",["Pokhara","Kathmandu","Lalitpur","Bharatpur"],1),
("easy","Which sport uses a BMX?",["Swimming","Bike tricks","Golf","Rowing"],1),
("easy","What is the capital of Sri Lanka?",["Kandy","Sri Jayawardenepura Kotte","Colombo","Galle"],1),
("easy","Which animal is the symbol of Kenya?",["Lion","Lion (on coat of arms)","Eagle","Bear"],1),
("easy","What is the capital of Bhutan?",["Paro","Thimphu","Punakha","Jakar"],1),
("easy","Which sport uses a skateboard ollie?",["Golf","Jump trick","Cricket","Swimming"],1),
("easy","What is the capital of Maldives?",["Malé","Addu","Fuvahmulah","Hulhumalé"],0),
("easy","Which animal is the symbol of Nigeria?",["Lion","Eagle (on coat of arms)","Bear","Tiger"],1),
("easy","What is the capital of Brunei?",["Bandar Seri Begawan","Kuala Belait","Tutong","Seria"],0),
("easy","Which sport uses a parkour?",["Golf","Urban movement","Cricket","Darts"],1),
("easy","What is the capital of East Timor?",["Baucau","Dili","Maliana","Suai"],1),
("easy","Which animal is the symbol of Egypt?",["Lion","Eagle (Saladin eagle)","Bear","Wolf"],1),
("easy","What is the capital of Papua New Guinea?",["Lae","Port Moresby","Madang","Goroka"],1),
("easy","Which sport uses a rock climbing wall?",["Swimming","Climbing","Golf","Rowing"],1),
("easy","What is the capital of Fiji?",["Lautoka","Suva","Nadi","Labasa"],1),
("easy","Which animal is the symbol of Morocco?",["Lion","Lion (Pavilion)","Eagle","Bear"],1),
("easy","What is the capital of Samoa?",["Apia","Salelologa","Asau","Mulifanua"],0),
("easy","Which sport uses a surfing wave?",["Golf","Riding waves","Cricket","Boxing"],1),
("easy","What is the capital of Tonga?",["Nuku'alofa","Neiafu","Pangai","Hihifo"],0),
("easy","Which animal is the symbol of Algeria?",["Lion","Fennec fox (unofficial)","Eagle","Bear"],1),
("easy","What is the capital of Vanuatu?",["Luganville","Port Vila","Isangel","Sola"],1),
("easy","Which sport uses a windsurfing board?",["Cricket","Sail on board","Golf","Darts"],1),
("easy","What is the capital of Solomon Islands?",["Gizo","Honiara","Auki","Tulagi"],1),
("easy","Which animal is the symbol of Tunisia?",["Lion","Lion and star","Eagle","Bear"],1),
("easy","What is the capital of Palau?",["Koror","Ngerulmud","Melekeok","Airai"],1),
("easy","Which sport uses a kitesurfing kite?",["Golf","Wind and board","Cricket","Rowing"],1),
("easy","What is the capital of Micronesia?",["Weno","Palikir","Kolonia","Tofol"],1),
("easy","Which animal is the symbol of Libya?",["Lion","Eagle","Bear","Wolf"],1),
("easy","What is the capital of Marshall Islands?",["Ebeye","Majuro","Jaluit","Wotje"],1),
("easy","Which sport uses a wakeboarding boat?",["Swimming","Towed on board","Golf","Cricket"],1),
("easy","What is the capital of Nauru?",["Yaren (de facto)","Yaren District","Aiwo","Anabar"],0),
("easy","Which animal is the symbol of Sudan?",["Lion","Secretary bird","Eagle","Bear"],1),
("easy","What is the capital of Tuvalu?",["Funafuti","Vaiaku","Asau","Savave"],0),
("easy","Which sport uses a water polo ball?",["Golf","Pool team sport","Cricket","Darts"],1),
("easy","What is the capital of Kiribati?",["Tarawa","South Tarawa","Betio","Bairiki"],0),
("easy","Which animal is the symbol of Ethiopia?",["Lion","Lion","Eagle","Bear"],0),
("easy","What is the capital of São Tomé and Príncipe?",["São Tomé","São Tomé city","Príncipe","Neves"],0),
("easy","Which sport uses a synchronised swimming?",["Golf","Swim in formation","Cricket","Boxing"],1),
("easy","What is the capital of Cape Verde?",["Mindelo","Praia","Sal","São Filipe"],1),
("easy","Which animal is the symbol of Ghana?",["Lion","Eagle (Black Star)","Bear","Tiger"],1),
("easy","What is the capital of Comoros?",["Moroni","Mutsamudu","Fomboni","Domoni"],0),
("easy","Which sport uses a diving platform?",["Golf","High board dive","Cricket","Rowing"],1),
("easy","What is the capital of Seychelles?",["Victoria","Anse Boileau","Beau Vallon","Takamaka"],0),
("easy","Which animal is the symbol of Senegal?",["Lion","Lion","Eagle","Bear"],0),
("easy","What is the capital of Mauritius?",["Port Louis","Curepipe","Vacoas","Beau Bassin"],0),
("easy","Which sport uses a open water swim?",["Pool only","Lake/sea swim","Golf","Darts"],1),
("easy","What is the capital of Madagascar?",["Toamasina","Antananarivo","Antsirabe","Mahajanga"],1),
("easy","Which animal is the symbol of Tanzania?",["Lion","Giraffe (tourism icon)","Eagle","Bear"],1),
("easy","What is the capital of Rwanda?",["Butare","Kigali","Gisenyi","Ruhengeri"],1),
("easy","Which sport uses a canoe sprint?",["Golf","Paddle racing","Cricket","Boxing"],1),
("easy","What is the capital of Uganda?",["Entebbe","Kampala","Jinja","Gulu"],1),
("easy","Which animal is the symbol of Zimbabwe?",["Lion","Zimbabwe bird","Eagle","Bear"],1),
("easy","What is the capital of Zambia?",["Ndola","Lusaka","Kitwe","Livingstone"],1),
("easy","Which sport uses a kayak slalom?",["Swimming","Gate course","Golf","Rowing"],1),
("easy","What is the capital of Malawi?",["Blantyre","Lilongwe","Mzuzu","Zomba"],1),
("easy","Which animal is the symbol of Botswana?",["Lion","Zebra (Coat)","Eagle","Bear"],1),
("easy","What is the capital of Mozambique?",["Beira","Maputo","Nampula","Tete"],1),
("easy","Which sport uses a rowing ergometer?",["Golf","Indoor row machine","Cricket","Darts"],1),
("easy","What is the capital of Angola?",["Lobito","Luanda","Huambo","Benguela"],1),
("easy","Which animal is the symbol of Namibia?",["Lion","Oryx","Eagle","Bear"],1),
("easy","What is the capital of Namibia?",["Swakopmund","Windhoek","Walvis Bay","Oshakati"],1),
("easy","Which sport uses a sailing regatta?",["Football","Boat racing","Cricket","Boxing"],1),
("easy","What is the capital of Botswana?",["Francistown","Gaborone","Maun","Serowe"],1),
("easy","Which animal is the symbol of Cameroon?",["Lion","Lion","Eagle","Bear"],0),
("easy","What is the capital of Cameroon?",["Douala","Yaoundé","Garoua","Bamenda"],1),
("easy","Which sport uses a windsurf sail?",["Golf","Wind power","Cricket","Rowing"],1),
("easy","What is the capital of Ivory Coast?",["Abidjan","Yamoussoukro","Bouaké","Daloa"],1),
("easy","Which animal is the symbol of Ivory Coast?",["Lion","Elephant","Eagle","Bear"],1),
("easy","What is the capital of Senegal?",["Saint-Louis","Dakar","Thiès","Kaolack"],1),
("easy","Which sport uses a horse jumping?",["Swimming","Equestrian","Golf","Cricket"],1),
("easy","What is the capital of Mali?",["Timbuktu","Bamako","Sikasso","Mopti"],1),
("easy","Which animal is the symbol of Mali?",["Lion","Vulture (emblem)","Eagle","Bear"],1),
("easy","What is the capital of Burkina Faso?",["Bobo-Dioulasso","Ouagadougou","Koudougou","Banfora"],1),
("easy","Which sport uses a dressage test?",["Football","Horse ballet","Cricket","Boxing"],1),
("easy","What is the capital of Niger?",["Zinder","Niamey","Maradi","Agadez"],1),
("easy","Which animal is the symbol of Niger?",["Lion","Zebu","Eagle","Bear"],1),
("easy","What is the capital of Chad?",["Faya","N'Djamena","Moundou","Abéché"],1),
("easy","Which sport uses a polo mallet?",["Golf","Horse polo","Cricket","Darts"],1),
("easy","What is the capital of Central African Republic?",["Bangui","Bimbo","Berbérati","Carnot"],0),
("easy","Which animal is the symbol of CAR?",["Lion","Elephant","Eagle","Bear"],1),
("easy","What is the capital of Congo (Brazzaville)?",["Pointe-Noire","Brazzaville","Dolisie","Nkayi"],1),
("easy","Which sport uses a rodeo?",["Swimming","Bull/calf events","Golf","Rowing"],1),
("easy","What is the capital of DRC?",["Lubumbashi","Kinshasa","Kisangani","Goma"],1),
("easy","Which animal is the symbol of DRC?",["Lion","Leopard","Eagle","Bear"],1),
("easy","What is the capital of Gabon?",["Port-Gentil","Libreville","Franceville","Oyem"],1),
("easy","Which sport uses a show jumping?",["Cricket","Horse fences","Golf","Boxing"],1),
("easy","What is the capital of Equatorial Guinea?",["Bata","Malabo","Ebebiyín","Mongomo"],1),
("easy","Which animal is the symbol of Equatorial Guinea?",["Lion","Silk cotton tree","Eagle","Bear"],1),
("easy","What is the capital of Guinea?",["Kankan","Conakry","Labé","Nzérékoré"],1),
("easy","Which sport uses a eventing?",["Golf","Three-day event","Cricket","Darts"],1),
("easy","What is the capital of Sierra Leone?",["Bo","Freetown","Kenema","Makeni"],1),
("easy","Which animal is the symbol of Sierra Leone?",["Lion","Lion","Eagle","Bear"],0),
("easy","What is the capital of Liberia?",["Buchanan","Monrovia","Gbarnga","Kakata"],1),
("easy","Which sport uses a archery target?",["Swimming","Bow and arrow","Golf","Rowing"],1),
("easy","What is the capital of Togo?",["Lomé","Sokodé","Kara","Atakpamé"],0),
("easy","Which animal is the symbol of Togo?",["Lion","Lion","Eagle","Bear"],0),
("easy","What is the capital of Benin?",["Cotonou","Porto-Novo","Parakou","Djougou"],1),
("easy","Which sport uses a taekwondo kick?",["Golf","Korean martial art","Cricket","Boxing"],1),
("easy","What is the capital of Gambia?",["Serekunda","Banjul","Brikama","Bakau"],1),
("easy","Which animal is the symbol of Gambia?",["Lion","Lion","Eagle","Bear"],0),
("easy","What is the capital of Guinea-Bissau?",["Bissau","Bafatá","Gabú","Cacheu"],0),
("easy","Which sport uses a judo throw?",["Swimming","Japanese martial art","Golf","Cricket"],1),
("easy","What is the capital of Eritrea?",["Massawa","Asmara","Assab","Keren"],1),
("easy","Which animal is the symbol of Eritrea?",["Lion","Camel (emblem)","Eagle","Bear"],1),
("easy","What is the capital of Djibouti?",["Djibouti City","Ali Sabieh","Tadjoura","Obock"],0),
("easy","Which sport uses a karate kata?",["Golf","Form routine","Cricket","Rowing"],1),
("easy","What is the capital of Somalia?",["Hargeisa","Mogadishu","Kismayo","Bosaso"],1),
("easy","Which animal is the symbol of Somalia?",["Lion","Leopard (star)","Eagle","Bear"],1),
("easy","What is the capital of South Sudan?",["Juba","Wau","Malakal","Yei"],0),
("easy","Which sport uses a boxing ring?",["Swimming","Fighting sport","Golf","Cricket"],1),
("easy","What is the capital of Eswatini?",["Manzini","Mbabane","Lobamba","Siteki"],1),
("easy","Which animal is the symbol of Eswatini?",["Lion","Lion and elephant","Eagle","Bear"],1),
("easy","What is the capital of Lesotho?",["Maseru","Teyateyaneng","Mafeteng","Hlotse"],0),
("easy","Which sport uses a wrestling mat?",["Golf","Grappling","Cricket","Darts"],1),
("easy","What is the capital of Mauritania?",["Nouadhibou","Nouakchott","Rosso","Kaédi"],1),
("easy","Which animal is the symbol of Mauritania?",["Lion","Star and crescent","Eagle","Bear"],1),
("easy","What is the capital of Western Sahara (disputed)?",["Laayoune","El Aaiún","Dakhla","Smara"],0),
("easy","Which sport uses a MMA cage?",["Swimming","Mixed martial arts","Golf","Rowing"],1),
("easy","What is the capital of Greenland (Denmark)?",["Nuuk","Sisimiut","Ilulissat","Qaqortoq"],0),
("easy","Which animal is the symbol of Greenland?",["Lion","Polar bear","Eagle","Bear"],1),
("easy","What is the capital of Faroe Islands?",["Tórshavn","Klaksvík","Runavík","Tvøroyri"],0),
("easy","Which sport uses a sumo ring?",["Golf","Japanese wrestling","Cricket","Boxing"],1),
("easy","What is the capital of Isle of Man?",["Douglas","Ramsey","Peel","Castletown"],0),
("easy","Which animal is the symbol of Isle of Man?",["Lion","Three legs","Eagle","Bear"],1),
("easy","What is the capital of Jersey?",["Saint Helier","Saint Peter","Gorey","St Aubin"],0),
("easy","Which sport uses a table tennis paddle?",["Golf","Ping pong","Cricket","Rowing"],1),
("easy","What is the capital of Guernsey?",["Saint Peter Port","St Sampson","Vale","Castel"],0),
("easy","Which animal is the symbol of Guernsey?",["Lion","Guernsey cow","Eagle","Bear"],1),
("easy","What is the capital of Gibraltar?",["Gibraltar (city)","La Línea","Algeciras","Ceuta"],0),
("easy","Which sport uses a squash court?",["Swimming","Racquet indoor","Golf","Cricket"],1),
("easy","What is the capital of Bermuda?",["Hamilton","St George's","Somerset","Flatts"],0),
("easy","Which animal is the symbol of Bermuda?",["Lion","Red lion","Eagle","Bear"],1),
("easy","What is the capital of Cayman Islands?",["George Town","West Bay","Bodden Town","East End"],0),
("easy","Which sport uses a racquetball?",["Golf","Wall racquet","Cricket","Darts"],1),
("easy","What is the capital of British Virgin Islands?",["Road Town","Spanish Town","Virgin Gorda","Tortola"],0),
("easy","Which animal is the symbol of BVI?",["Lion","St Ursula","Eagle","Bear"],1),
("easy","What is the capital of Anguilla?",["The Valley","Blowing Point","Sandy Ground","Island Harbour"],0),
("easy","Which sport uses a lacrosse stick?",["Swimming","Stick and net","Golf","Rowing"],1),
("easy","What is the capital of Montserrat?",["Brades","Plymouth (abandoned)","Little Bay","Salem"],0),
("easy","Which animal is the symbol of Montserrat?",["Lion","Lady with harp","Eagle","Bear"],1),
("easy","What is the capital of Turks and Caicos?",["Cockburn Town","Providenciales","Grand Turk","South Caicos"],0),
("easy","Which sport uses a handball goal?",["Golf","Team hand sport","Cricket","Boxing"],1),
("easy","What is the capital of Saint Kitts and Nevis?",["Basseterre","Charlestown","Sandy Point","Cayon"],0),
("easy","Which animal is the symbol of Saint Kitts?",["Lion","Pelican","Eagle","Bear"],1),
("easy","What is the capital of Antigua and Barbuda?",["St John's","All Saints","Liberta","English Harbour"],0),
("easy","Which sport uses a netball hoop?",["Football","Women's team sport","Golf","Cricket"],1),
("easy","What is the capital of Dominica?",["Roseau","Portsmouth","Marigot","Mahaut"],0),
("easy","Which animal is the symbol of Dominica?",["Lion","Sisserou parrot","Eagle","Bear"],1),
("easy","What is the capital of Saint Lucia?",["Castries","Vieux Fort","Soufrière","Gros Islet"],0),
("easy","Which sport uses a floorball?",["Swimming","Indoor hockey","Golf","Rowing"],1),
("easy","What is the capital of Saint Vincent?",["Kingstown","Georgetown","Barrouallie","Layou"],0),
("easy","Which animal is the symbol of Saint Vincent?",["Lion","Dove","Eagle","Bear"],1),
("easy","What is the capital of Grenada?",["St George's","Gouyave","Grenville","Sauteurs"],0),
("easy","Which sport uses a roller derby?",["Golf","Skating contact","Cricket","Darts"],1),
("easy","What is the capital of Aruba?",["Oranjestad","San Nicolas","Noord","Santa Cruz"],0),
("easy","Which animal is the symbol of Aruba?",["Lion","Four-point star","Eagle","Bear"],1),
("easy","What is the capital of Curaçao?",["Willemstad","Sint Michiel","Barber","Dorp Soto"],0),
("easy","Which sport uses a ice skating jump?",["Swimming","Axel/toe loop","Golf","Cricket"],1),
("easy","What is the capital of Sint Maarten?",["Philipsburg","Simpson Bay","Cul de Sac","Lower Prince"],0),
("easy","Which animal is the symbol of Sint Maarten?",["Lion","Brown pelican","Eagle","Bear"],1),
("easy","What is the capital of French Guiana?",["Cayenne","Kourou","Saint-Laurent","Matoury"],0),
("easy","Which sport uses a figure skating spin?",["Golf","Ice spin","Cricket","Rowing"],1),
("easy","What is the capital of Guadeloupe?",["Basse-Terre","Pointe-à-Pitre","Les Abymes","Le Gosier"],0),
("easy","Which animal is the symbol of Guadeloupe?",["Lion","Sunbird","Eagle","Bear"],1),
("easy","What is the capital of Martinique?",["Fort-de-France","Le Lamentin","Le Robert","Schoelcher"],0),
("easy","Which sport uses a speed skating?",["Swimming","Ice oval race","Golf","Cricket"],1),
("easy","What is the capital of Réunion?",["Saint-Denis","Saint-Paul","Le Tampon","Saint-Pierre"],0),
("easy","Which animal is the symbol of Réunion?",["Lion","White tropicbird","Eagle","Bear"],1),
("easy","What is the capital of Mayotte?",["Mamoudzou","Dzaoudzi","Koungou","Dembeni"],0),
("easy","Which sport uses a short track skating?",["Golf","Tight ice oval","Cricket","Darts"],1),
("easy","What is the capital of New Caledonia?",["Nouméa","Mont-Dore","Dumbéa","Païta"],0),
("easy","Which animal is the symbol of New Caledonia?",["Lion","Kagu bird","Eagle","Bear"],1),
("easy","What is the capital of French Polynesia?",["Papeete","Faaa","Punaauia","Moorea"],0),
("easy","Which sport uses a snowboarding halfpipe?",["Swimming","Winter ramp","Golf","Rowing"],1),
("easy","What is the capital of Wallis and Futuna?",["Mata-Utu","Leava","Sigave","Alo"],0),
("easy","Which animal is the symbol of Wallis?",["Lion","Red flag","Eagle","Bear"],1),
("easy","What is the capital of American Samoa?",["Pago Pago","Fagatogo","Tafuna","Leone"],0),
("easy","Which sport uses a alpine skiing?",["Golf","Downhill ski","Cricket","Boxing"],1),
("easy","What is the capital of Guam?",["Hagåtña","Dededo","Tamuning","Mangilao"],0),
("easy","Which animal is the symbol of Guam?",["Lion","Coconut tree","Eagle","Bear"],1),
("easy","What is the capital of Northern Mariana Islands?",["Saipan","Garapan","Tinian","Rota"],0),
("easy","Which sport uses a cross-country skiing?",["Swimming","Flat snow ski","Golf","Cricket"],1),
("easy","What is the capital of Puerto Rico?",["San Juan","Bayamón","Carolina","Ponce"],0),
("easy","Which animal is the symbol of Puerto Rico?",["Lion","Coqui frog (unofficial)","Eagle","Bear"],1),
("easy","What is the capital of US Virgin Islands?",["Charlotte Amalie","Christiansted","Frederiksted","Cruz Bay"],0),
("easy","Which sport uses a freestyle skiing?",["Golf","Tricks on snow","Cricket","Rowing"],1),
("easy","What is the capital of Cook Islands?",["Avarua","Arutanga","Matavera","Amuri"],0),
("easy","Which animal is the symbol of Cook Islands?",["Lion","Fifteen stars","Eagle","Bear"],1),
("easy","What is the capital of Niue?",["Alofi","Avatele","Tamakautoga","Lakepa"],0),
("easy","Which sport uses a nordic combined?",["Swimming","Ski jump + XC","Golf","Darts"],1),
("easy","What is the capital of Tokelau?",["Atafu","Nukunonu","Fakaofo","Each atoll"],0),
("easy","Which animal is the symbol of Tokelau?",["Lion","Tokelauan canoe","Eagle","Bear"],1),
("easy","What is the capital of Pitcairn Islands?",["Adamstown","Bounty Bay","Tedside","Hill of Difficulty"],0),
("easy","Which sport uses a ski mountaineering?",["Golf","Climb and ski","Cricket","Boxing"],1),
("easy","What is the capital of Saint Helena?",["Jamestown","Half Tree Hollow","Longwood","Levelwood"],0),
("easy","Which animal is the symbol of Saint Helena?",["Lion","Wirebird","Eagle","Bear"],1),
("easy","What is the capital of Ascension Island?",["Georgetown","Two Boats","Traveller's Hill","English Bay"],0),
("easy","Which sport uses a telemark skiing?",["Swimming","Free-heel turn","Golf","Cricket"],1),
("easy","What is the capital of Tristan da Cunha?",["Edinburgh of the Seven Seas","Calshot Harbour","Halfway Beach","Potato Patch"],0),
("easy","Which animal is the symbol of Tristan?",["Lion","Tristan albatross","Eagle","Bear"],1),
("easy","What is the capital of Falkland Islands?",["Stanley","Goose Green","Port Howard","Fox Bay"],0),
("easy","Which sport uses a snowshoe running?",["Golf","Run on snowshoes","Cricket","Rowing"],1),
("easy","What is the capital of South Georgia?",["Grytviken","King Edward Point","Stromness","Leith Harbour"],0),
("easy","Which animal is the symbol of South Georgia?",["Lion","Reindeer (introduced)","Eagle","Bear"],1),
("easy","What is the capital of British Antarctic Territory?",["Rothera","Halley","Port Lockroy","No permanent capital"],0),
("easy","Which sport uses a ice climbing?",["Swimming","Climb ice","Golf","Cricket"],1),
("easy","What is the capital of French Southern Territories?",["Port-aux-Français","Alfred Faure","No cities","Amsterdam Island"],0),
("easy","Which animal is the symbol of French Southern?",["Lion","Penguin colonies","Eagle","Bear"],1),
("easy","What is the capital of Heard Island?",["No permanent population","Atlas Cove","Spit Bay","Corinthian Bay"],0),
("easy","Which sport uses a orienteering map?",["Golf","Navigation race","Cricket","Darts"],1),
("easy","What is the capital of McDonald Islands?",["Uninhabited","Heard nearby","No capital","Southern Ocean"],0),
("easy","Which animal is the symbol of McDonald?",["Lion","Seal colonies","Eagle","Bear"],1),
("easy","What is the capital of Bouvet Island?",["Uninhabited","Norwegian claim","No capital","South Atlantic"],0),
("easy","Which sport uses a geocaching GPS?",["Swimming","Treasure hunt","Golf","Rowing"],1),
("easy","What is the capital of Svalbard?",["Longyearbyen","Barentsburg","Ny-Ålesund","Sveagruva"],0),
("easy","Which animal is the symbol of Svalbard?",["Lion","Polar bear","Eagle","Bear"],1),
("easy","What is the capital of Jan Mayen?",["Olonkinbyen","Beerenberg","No real capital","Arctic"],0),
("easy","Which sport uses a adventure racing?",["Golf","Multi-discipline","Cricket","Boxing"],1),
("easy","What is the capital of Åland?",["Mariehamn","Jomala","Finström","Godby"],0),
("easy","Which animal is the symbol of Åland?",["Lion","Red deer","Eagle","Bear"],1),
("easy","What is the capital of Ceuta?",["Ceuta","Melilla","Algeciras","Tangier"],0),
("easy","Which sport uses a trail running?",["Swimming","Off-road run","Golf","Cricket"],1),
("easy","What is the capital of Melilla?",["Melilla","Ceuta","Nador","Oujda"],0),
("easy","Which animal is the symbol of Melilla?",["Lion","Royal crown","Eagle","Bear"],1),
("easy","What is the capital of Canary Islands (Spain)?",["Las Palmas / Santa Cruz","Tenerife only","Lanzarote","Fuerteventura"],0),
("easy","Which sport uses a ultramarathon?",["5 km","Beyond marathon","Swimming","Golf"],1),
("easy","What is the capital of Madeira?",["Funchal","Câmara de Lobos","Machico","Santa Cruz"],0),
("easy","Which animal is the symbol of Madeira?",["Lion","Trocaz pigeon","Eagle","Bear"],1),
("easy","What is the capital of Azores?",["Ponta Delgada","Angra","Horta","Ribeira Grande"],0),
("easy","Which sport uses a ironman triathlon?",["Sprint only","Long triathlon","Golf","Cricket"],1),
("easy","What is the capital of Balearic Islands?",["Palma","Ibiza Town","Mahón","Ciutadella"],0),
("easy","Which animal is the symbol of Balearics?",["Lion","Mallorcan midwife toad","Eagle","Bear"],1),
("easy","What is the capital of Corsica?",["Ajaccio","Bastia","Porto-Vecchio","Calvi"],0),
("easy","Which sport uses a duathlon?",["Swim-bike","Run-bike-run","Golf","Darts"],1),
("easy","What is the capital of Sardinia?",["Cagliari","Sassari","Olbia","Alghero"],0),
("easy","Which animal is the symbol of Sardinia?",["Lion","Mouflon","Eagle","Bear"],1),
("easy","What is the capital of Sicily?",["Palermo","Catania","Messina","Syracuse"],0),
("easy","Which sport uses a aquathlon?",["Bike only","Swim-run","Golf","Cricket"],1),
("easy","What is the capital of Crete?",["Heraklion","Chania","Rethymno","Agios Nikolaos"],0),
("easy","Which animal is the symbol of Crete?",["Lion","Kri-kri goat","Eagle","Bear"],1),
("easy","What is the capital of Rhodes?",["Rhodes Town","Lindos","Ialysos","Faliraki"],0),
("easy","Which sport uses a swimrun?",["Pool","Alternating swim run","Golf","Rowing"],1),
("easy","What is the capital of Isle of Wight?",["Newport","Ryde","Cowes","Sandown"],0),
("easy","Which animal is the symbol of Isle of Wight?",["Lion","Red squirrel","Eagle","Bear"],1),
("easy","What is the capital of Shetland?",["Lerwick","Scalloway","Sumburgh","Walls"],0),
("easy","Which sport uses a obstacle course race?",["Golf","Mud run","Cricket","Boxing"],1),
("easy","What is the capital of Orkney?",["Kirkwall","Stromness","St Margaret's Hope","Dounby"],0),
("easy","Which animal is the symbol of Orkney?",["Lion","Orkney vole","Eagle","Bear"],1),
("easy","What is the capital of Outer Hebrides?",["Stornoway","Tarbert","Lochmaddy","Balivanich"],0),
("easy","Which sport uses a Spartan race?",["Swimming","Obstacle series","Golf","Cricket"],1),
("easy","What is the capital of Inner Hebrides?",["Portree","Tobermory","Bowmore","Lochboisdale"],0),
("easy","Which animal is the symbol of Inner Hebrides?",["Lion","Red deer","Eagle","Bear"],1),
("easy","What is the capital of Anglesey?",["Llangefni","Holyhead","Beaumaris","Amlwch"],0),
("easy","Which sport uses a Tough Mudder?",["Golf","Team obstacles","Cricket","Darts"],1),
("easy","What is the capital of Skye?",["Portree","Broadford","Kyleakin","Uig"],0),
("easy","Which animal is the symbol of Skye?",["Lion","Golden eagle","Eagle","Bear"],1),
("easy","What is the capital of Channel Islands (combined)?",["St Helier / St Peter Port","Jersey only","Guernsey only","Sark"],0),
("easy","Which sport uses a color run?",["Swimming","Paint powder run","Golf","Rowing"],1),
("easy","What is the capital of Sark?",["La Seigneurie area","No cars","Small island","Channel Islands"],0),
("easy","Which animal is the symbol of Sark?",["Lion","Guernsey cow","Eagle","Bear"],1),
("easy","What is the capital of Alderney?",["St Anne","Braye","Longis","Mannez"],0),
("easy","Which sport uses a parkrun?",["Paid race","Free 5K","Golf","Cricket"],1),
("easy","What is the capital of Herm?",["No town","Tiny island","Guernsey nearby","Channel"],0),
("easy","Which animal is the symbol of Herm?",["Lion","Atlantic puffin","Eagle","Bear"],1),
("easy","What is the capital of Lundy?",["No permanent residents","Bristol Channel","Island","Devon"],0),
("easy","Which sport uses a couch to 5K?",["Olympic","Beginner programme","Golf","Darts"],1),
("easy","What is the capital of Rathlin Island?",["Church Bay","Northern Ireland","Island","Antrim"],0),
("easy","Which animal is the symbol of Rathlin?",["Lion","Seabirds","Eagle","Bear"],1),
("easy","What is the capital of Aran Islands?",["Kilronan","Inishmore","Galway Bay","Ireland"],0),
("easy","Which sport uses a HIIT workout?",["Slow walk","High intensity intervals","Golf","Cricket"],1),
("easy","What is the capital of Achill Island?",["Keel","Dooagh","Mayo","Ireland"],0),
("easy","Which animal is the symbol of Achill?",["Lion","Basking shark (waters)","Eagle","Bear"],1),
("easy","What is the capital of Valletta Malta?",["Valletta","Mdina","Sliema","Gozo Victoria"],0),
("easy","Which sport uses a CrossFit WOD?",["Chess","Workout of day","Golf","Rowing"],1),
("easy","What is the capital of Gozo?",["Victoria (Rabat)","Xaghra","Nadur","Marsalforn"],0),
("easy","Which animal is the symbol of Gozo?",["Lion","Mediterranean monk seal","Eagle","Bear"],1),
("easy","What is the capital of Isle of Man TT?",["Douglas","Ramsey","Peel","Onchan"],0),
("easy","Which sport uses a spinning class?",["Swimming","Indoor cycling","Golf","Cricket"],1),
("easy","What is the capital of Lindisfarne?",["Holy Island","Northumberland","Tidal","England"],0),
("easy","Which animal is the symbol of Lindisfarne?",["Lion","Grey seals","Eagle","Bear"],1),
("easy","What is the capital of St Kilda?",["Uninhabited","Scotland","Archipelago","Hebrides"],0),
("easy","Which sport uses a pilates mat?",["Weightlifting","Core exercise","Golf","Darts"],1),
("easy","What is the capital of Fair Isle?",["No capital","Shetland","Bird observatory","Scotland"],0),
("easy","Which animal is the symbol of Fair Isle?",["Lion","Puffins","Eagle","Bear"],1),
("easy","What is the capital of Foula?",["Hametoun","Shetland","Remote","Scotland"],0),
("easy","Which sport uses a yoga flow?",["Sprint","Mind-body","Golf","Cricket"],1),
("easy","What is the capital of Unst?",["Baltasound","Shetland","Northernmost UK","Scotland"],0),
("easy","Which animal is the symbol of Unst?",["Lion","Otters","Eagle","Bear"],1),
("easy","What is the capital of Yell?",["Mid Yell","Shetland","Island","Scotland"],0),
("easy","Which sport uses a zumba dance?",["Silent","Dance fitness","Golf","Rowing"],1),
("easy","What is the capital of Fetlar?",["Tresta","Shetland","Island","Scotland"],0),
("easy","Which animal is the symbol of Fetlar?",["Lion","Red-necked phalarope","Eagle","Bear"],1),
("easy","What is the capital of Papa Stour?",["Biggings","Shetland","Small","Scotland"],0),
("easy","Which sport uses a barre workout?",["Swimming","Ballet-inspired","Golf","Cricket"],1),
("easy","What is the capital of Mousa?",["Uninhabited broch","Shetland","Island","Scotland"],0),
("easy","Which animal is the symbol of Mousa?",["Lion","Storm petrels","Eagle","Bear"],1),
("easy","What is the capital of Hoy?",["Lyness","Orkney","Island","Scotland"],0),
("easy","Which sport uses a kettlebell swing?",["Chess","Weight exercise","Golf","Darts"],1),
("easy","What is the capital of Westray?",["Pierowall","Orkney","Island","Scotland"],0),
("easy","Which animal is the symbol of Westray?",["Lion","Corncrake (historic)","Eagle","Bear"],1),
("easy","What is the capital of Sanday?",["Lady Village","Orkney","Island","Scotland"],0),
("easy","Which sport uses a TRX straps?",["Swimming","Suspension training","Golf","Cricket"],1),
("easy","What is the capital of Stronsay?",["Whitehall","Orkney","Island","Scotland"],0),
("easy","Which animal is the symbol of Stronsay?",["Lion","Seals","Eagle","Bear"],1),
("easy","What is the capital of Eday?",["Backaland","Orkney","Island","Scotland"],0),
("easy","Which sport uses a rowing machine?",["Golf","Ergometer","Cricket","Boxing"],1),
("easy","What is the capital of North Ronaldsay?",["Hooking Centre","Orkney","Seaweed sheep","Scotland"],0),
("easy","Which animal is the symbol of North Ronaldsay?",["Lion","Seaweed-eating sheep","Eagle","Bear"],1),
("easy","What is the capital of Coll?",["Arinagour","Inner Hebrides","Island","Scotland"],0),
("easy","Which sport uses a stair climber?",["Swimming","Step machine","Golf","Rowing"],1),
("easy","What is the capital of Tiree?",["Scarinish","Inner Hebrides","Island","Scotland"],0),
("easy","Which animal is the symbol of Tiree?",["Lion","Corncrake","Eagle","Bear"],1),
("easy","What is the capital of Colonsay?",["Scalasaig","Inner Hebrides","Island","Scotland"],0),
("easy","Which sport uses a elliptical trainer?",["Golf","Low-impact cardio","Cricket","Darts"],1),
("easy","What is the capital of Islay?",["Bowmore","Port Charlotte","Inner Hebrides","Scotland"],0),
("easy","Which animal is the symbol of Islay?",["Lion","Chough","Eagle","Bear"],1),
("easy","What is the capital of Jura?",["Craighouse","Inner Hebrides","Island","Scotland"],0),
("easy","Which sport uses a treadmill incline?",["Swimming","Indoor run","Golf","Cricket"],1),
("easy","What is the capital of Mull?",["Tobermory","Craignure","Inner Hebrides","Scotland"],0),
("easy","Which animal is the symbol of Mull?",["Lion","White-tailed eagle","Eagle","Bear"],1),
("easy","What is the capital of Iona?",["Baile Mòr","Inner Hebrides","Abbey","Scotland"],0),
("easy","Which sport uses a jump rope?",["Golf","Skipping","Cricket","Rowing"],1),
("easy","What is the capital of Staffa?",["Uninhabited","Fingal's Cave","Inner Hebrides","Scotland"],0),
("easy","Which animal is the symbol of Staffa?",["Lion","Puffins","Eagle","Bear"],1),
("easy","What is the capital of Lismore?",["Achnacroish","Inner Hebrides","Island","Scotland"],0),
("easy","Which sport uses a battle ropes?",["Chess","Heavy rope waves","Golf","Darts"],1),
("easy","What is the capital of Eigg?",["Cleadale","Small Isles","Island","Scotland"],0),
("easy","Which animal is the symbol of Eigg?",["Lion","Golden eagle","Eagle","Bear"],1),
("easy","What is the capital of Rum?",["Kinloch","Small Isles","Island","Scotland"],0),
("easy","Which sport uses a medicine ball slam?",["Swimming","Weighted ball","Golf","Cricket"],1),
("easy","What is the capital of Muck?",["Port Mòr","Small Isles","Island","Scotland"],0),
("easy","Which animal is the symbol of Muck?",["Lion","Seabirds","Eagle","Bear"],1),
("easy","What is the capital of Canna?",["Keill","Small Isles","Island","Scotland"],0),
("easy","Which sport uses a resistance band?",["Golf","Elastic training","Cricket","Boxing"],1),
("easy","What is the capital of Sanday (Small Isles)?",["No — different Sanday","Orkney has Sanday","Small Isles","Scotland"],0),
("easy","Which animal is the symbol of Canna?",["Lion","Manx shearwater","Eagle","Bear"],1),
("easy","What is the capital of Raasay?",["Inverarish","Inner Hebrides","Island","Scotland"],0),
("easy","Which sport uses a foam roller?",["Sprint","Self-massage","Golf","Rowing"],1),
("easy","What is the capital of Scalpay?",["Out Skye","Harris link","Island","Scotland"],0),
("easy","Which animal is the symbol of Raasay?",["Lion","Red deer","Eagle","Bear"],1),
("easy","What is the capital of Great Bernera?",["Breaclete","Outer Hebrides","Island","Scotland"],0),
("easy","Which sport uses a agility ladder?",["Swimming","Footwork drills","Golf","Cricket"],1),
("easy","What is the capital of Vatersay?",["Vatersay","Outer Hebrides","Island","Scotland"],0),
("easy","Which animal is the symbol of Vatersay?",["Lion","Otters","Eagle","Bear"],1),
("easy","What is the capital of Barra?",["Castlebay","Outer Hebrides","Island","Scotland"],0),
("easy","Which sport uses a cone drill?",["Golf","Marker drills","Cricket","Darts"],1),
("easy","What is the capital of South Uist?",["Lochboisdale","Outer Hebrides","Island","Scotland"],0),
("easy","Which animal is the symbol of South Uist?",["Lion","Corncrake","Eagle","Bear"],1),
("easy","What is the capital of Benbecula?",["Balivanich","Outer Hebrides","Island","Scotland"],0),
("easy","Which sport uses a sled push?",["Swimming","Weighted sled","Golf","Cricket"],1),
("easy","What is the capital of North Uist?",["Lochmaddy","Outer Hebrides","Island","Scotland"],0),
("easy","Which animal is the symbol of North Uist?",["Lion","Hen harrier","Eagle","Bear"],1),
("easy","What is the capital of Harris?",["Tarbert","Outer Hebrides","Island","Scotland"],0),
("easy","Which sport uses a tire flip?",["Chess","Strongman move","Golf","Rowing"],1),
("easy","What is the capital of Lewis?",["Stornoway","Outer Hebrides","Island","Scotland"],0),
("easy","Which animal is the symbol of Lewis?",["Lion","Red deer","Eagle","Bear"],1),
("easy","What is the capital of St Kilda (repeat guard)?",["Uninhabited","Scotland","UNESCO","Hebrides"],0),
("easy","Which sport uses a farmer's walk?",["Swimming","Carry weights","Golf","Cricket"],1),
("easy","What is the capital of Fair Isle (repeat guard)?",["Bird observatory","Shetland","Island","Scotland"],0),
("easy","Which animal is the symbol of Fair Isle?",["Lion","Puffins","Eagle","Bear"],1),
("easy","What is the capital of Rockall?",["Uninhabited rock","North Atlantic","No capital","UK claim"],0),
("easy","Which sport uses a atlas stones?",["Golf","Strongman lift","Cricket","Boxing"],1),
("easy","What is the capital of Heligoland?",["Heligoland","German island","North Sea","No UK"],0),
("easy","Which animal is the symbol of Heligoland?",["Lion","Grey seal","Eagle","Bear"],1),
("easy","What is the capital of Channel Island Sark?",["La Seigneurie","No cars","Small","Crown"],0),
("easy","Which sport uses a log press?",["Swimming","Overhead log","Golf","Darts"],1),
("easy","What is the capital of Isle of Man?",["Douglas","Peel","Ramsey","Castletown"],0),
("easy","Which animal is the symbol of Isle of Man?",["Lion","Three legs triskelion","Eagle","Bear"],1),
("easy","What is the capital of Jersey?",["Saint Helier","Saint Peter","Gorey","Trinity"],0),
("easy","Which sport uses a caber toss?",["Golf","Highland games","Cricket","Rowing"],1),
("easy","What is the capital of Guernsey?",["Saint Peter Port","St Sampson","Vale","Forest"],0),
("easy","Which animal is the symbol of Guernsey?",["Lion","Guernsey cow","Eagle","Bear"],1),
("easy","What is the capital of Northern Ireland?",["Belfast","Derry","Lisburn","Newry"],0),
("easy","Which sport uses a hammer throw (Highland)?",["Swimming","Heavy hammer","Golf","Cricket"],1),
("easy","What is the capital of Republic of Ireland?",["Dublin","Cork","Galway","Limerick"],0),
("easy","Which animal is the symbol of Ireland?",["Lion","Harp","Eagle","Bear"],1),
("easy","What is the capital of Scotland?",["Edinburgh","Glasgow","Aberdeen","Dundee"],0),
("easy","Which sport uses a stone put?",["Golf","Highland games","Cricket","Darts"],1),
("easy","What is the capital of Wales?",["Cardiff","Swansea","Newport","Wrexham"],0),
("easy","Which animal is the symbol of Wales?",["Lion","Red dragon","Eagle","Bear"],1),
("easy","What is the capital of England?",["London","Birmingham","Manchester","Leeds"],0),
("easy","Which sport uses a sheaf toss?",["Swimming","Burlap bag","Golf","Rowing"],1),
("easy","What is the capital of United Kingdom?",["London","Edinburgh","Cardiff","Belfast"],0),
("easy","Which animal is the symbol of UK?",["Lion","Lion and unicorn","Eagle","Bear"],1),
]
# fmt: on

def main() -> None:
    seen_q: set[str] = set()
    bank: list[dict] = []
    counters = {"easy": 0, "medium": 0, "hard": 0, "expert": 0}

    for diff, q, opts, ans in QUESTIONS:
        key = q.strip().lower()
        if key in seen_q:
            continue
        seen_q.add(key)
        counters[diff] = counters.get(diff, 0) + 1
        prefix = {"easy": "e", "medium": "m", "hard": "h", "expert": "x"}.get(diff, "q")
        bank.append({
            "id": f"{prefix}{counters[diff]:04d}",
            "d": diff,
            "q": q,
            "o": opts,
            "a": ans,
        })

    # Load legacy questions from existing file if present
    legacy_path = OUT
    if legacy_path.exists():
        import re
        text = legacy_path.read_text(encoding="utf-8")
        for m in re.finditer(r'\{d:"(\w+)",q:"((?:\\.|[^"\\])*)",o:\[(.*?)\],a:(\d+)\}', text):
            diff, q, o_raw, ans = m.group(1), m.group(2), m.group(3), int(m.group(4))
            q = q.encode().decode("unicode_escape") if "\\" in q else q
            key = q.strip().lower()
            if key in seen_q:
                continue
            seen_q.add(key)
            opts = [m.group(1).replace('\\"', '"') for m in re.finditer(r'"((?:\\.|[^"\\])*)"', o_raw)]
            if len(opts) != 4:
                continue
            counters[diff] = counters.get(diff, 0) + 1
            prefix = {"easy": "e", "medium": "m", "hard": "h", "expert": "x"}.get(diff, "q")
            bank.append({"id": f"{prefix}{counters[diff]:04d}", "d": diff, "q": q, "o": opts, "a": ans})

    lines = [
        "/** Original question bank — fan-made demo, not from any TV show. */",
        f"window.QUIZ_BANK = {json.dumps(bank, ensure_ascii=False, indent=2)};",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(bank)} unique questions to {OUT}")
    from collections import Counter
    print("By difficulty:", dict(Counter(x["d"] for x in bank)))


if __name__ == "__main__":
    main()
